# Pre-commit configuration for ama_ws25 project
# Install: uv run pre-commit install
# Run manually: uv run pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter (replaces black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        name: Ruff lint (auto-fix)
      # Run the formatter
      - id: ruff-format
        name: Ruff format

  # Python-specific checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
        name: Check TOML syntax
      - id: end-of-file-fixer
        name: Fix end of files
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: check-added-large-files
        args: [--maxkb=1000]
        name: Check for large files
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: mixed-line-ending
        name: Fix mixed line endings

  # # Type checking with mypy
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       name: MyPy type checking
  #       additional_dependencies:
  #         - pandas-stubs
  #         - types-seaborn
  #       args: [--config-file=ama_tlbx/pyproject.toml]
  #       files: ^ama_tlbx/src/

  # # Run pytest tests
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: Run pytest tests
  #       entry: bash -c 'cd ama_tlbx && uv run pytest tests/ -v --tb=short'
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #       stages: [commit]


# Configuration
ci:
  autofix_prs: true
  autoupdate_schedule: weekly
